### ISSUE TITLE
Use flexbox instead of floats

### ISSUE THREAD

**Issue by chrzrdx** [haripriya12/edyst-s19-choose-a-pokemon#3]
https://github.com/haripriya12/edyst-s19-choose-a-pokemon/blob/978734f4956dfe2e58372e6c2672e33dc603fa78/frontend/index.html#L8

see: https://medium.freecodecamp.org/an-animated-guide-to-flexbox-d280cf6afc35

**Comment by haripriya12** [comment]
used flexbox instead of floats
